image:
  file: .gitpod.Dockerfile

ports:
  - port: 5984
    onOpen: ignore
    visibility: public
  - port: 6363
    onOpen: ignore
    visibility: public

tasks:
  - init: docker build -t hyper-couch .couchdb
    command: |
      docker run -it -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password hyper-couch
  - command: |
      git config core.hooksPath .hooks
      clear

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
