image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start CouchDB
    init: docker build -t hyper-couch .couchdb
    command: |
      docker run -it -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password hyper-couch

  - name: Set Git Hooks
    init: deno task prepare

ports:
  - port: 5984
    onOpen: ignore
    visibility: public
  - port: 6363
    onOpen: ignore
    visibility: public
