name: Test CouchDB Adapter
on:
  push:
    branches-ignore: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.11.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version}}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: ./scripts/test.sh
        env:
          CI: true
